<!-- Adicionando JQuery    -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<!-- Adicionando Javascript -->
<script>
    $(document).ready(function() {

        function limpa_formulário_cep() {
            // Limpa valores do formulário de cep.
            $("#rua").val("");
            $("#bairro").val("");
            $("#cidade").val("");
            $("#uf").val("");
            $("#ibge").val("");
        }

        //Quando o campo cep perde o foco.
        $("#cep").blur(function() {

            //Nova variável "cep" somente com dígitos.
            var cep = $(this).val().replace(/\D/g, '');

            //Verifica se campo cep possui valor informado.
            if (cep != "") {

                //Expressão regular para validar o CEP.
                var validacep = /^[0-9]{8}$/;

                //Valida o formato do CEP.
                if (validacep.test(cep)) {

                    //Preenche os campos com "..." enquanto consulta webservice.
                    $("#rua").val("...");
                    $("#bairro").val("...");
                    $("#cidade").val("...");
                    $("#uf").val("...");
                    $("#ibge").val("...");

                    //Consulta o webservice viacep.com.br/
                    $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function(dados) {

                        if (!("erro" in dados)) {
                            //Atualiza os campos com os valores da consulta.
                            $("#rua").val(dados.logradouro);
                            $("#bairro").val(dados.bairro);
                            $("#cidade").val(dados.localidade);
                            $("#uf").val(dados.uf);
                            $("#ibge").val(dados.ibge);
                        } //end if.
                        else {
                            //CEP pesquisado não foi encontrado.
                            limpa_formulário_cep();
                            alert("CEP não encontrado.");
                        }
                    });
                } //end if.
                else {
                    //cep é inválido.
                    limpa_formulário_cep();
                    alert("Formato de CEP inválido.");
                }
            } //end if.
            else {
                //cep sem valor, limpa formulário.
                limpa_formulário_cep();
            }
        });
    });
</script>
<div class="row">
    <div class="col-xs-12 col-xs-offset-0">
        <div>
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->getPageTitle() ?></h3>
            </div>
            <div class="panel-body">
                <form action="/user/<?php echo $this->view->user->id ?>/update" method="post" accept-charset="utf-8">
                    <div class="form-group <?php echo ($this->errors['name']) ? 'has-error' : ''; ?> col-md-3 col-md-offset-0">
                        <label for="name">Usuário</label>
                        <input type="text" name="name" class="form-control" value="<?php echo (isset($this->inputs['name'])) ? $this->inputs['name'] : $this->view->user->name; ?>" />
                        <?php if ($this->errors['name']) : ?>
                            <span class="help-block"><?php echo $this->errors['name'] ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="form-group <?php echo ($this->errors['password']) ? 'has-error' : ''; ?> col-md-3 col-md-offset-0">
                        <label for="password">Senha</label>
                        <input type="password" name="password" class="form-control" placeholder='mudar a senha' />
                        <?php if ($this->errors['password']) : ?>
                            <span class="help-block"><?php echo $this->errors['password'] ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="form-group <?php echo ($this->errors['phone']) ? 'has-error' : ''; ?> col-md-3 col-md-offset-0">
                        <label for="phone">Telefone</label>
                        <input type="text" name="phone" class="form-control" value="<?php echo (isset($this->inputs['phone'])) ? $this->inputs['phone'] : $this->view->user->phone; ?>" />
                        <?php if ($this->errors['phone']) : ?>
                            <span class="help-block"><?php echo $this->errors['phone'] ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="form-group <?php echo ($this->errors['expires']) ? 'has-error' : ''; ?> col-md-3 col-md-offset-0">
                        <label for="expires">Vencimento</label>
                        <input <?php echo ($this->auth->admin()) ? "type='date'" : "type='text' readonly" ?> name="expires" class="form-control" value="<?php echo (isset($this->inputs['expires'])) ? $this->inputs['expires'] : $this->view->user->expires; ?>" />
                        <?php if ($this->errors['expires']) : ?>
                            <span class="help-block"><?php echo $this->errors['expires'] ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="form-group <?php echo ($this->errors['email']) ? 'has-error' : ''; ?> col-md-12 col-md-offset-0">
                        <label for="email">Email</label>
                        <input type="email" name="email" class="form-control" value="<?php echo (isset($this->inputs['email'])) ? $this->inputs['email'] : $this->view->user->email; ?>" />
                        <?php if ($this->errors['email']) : ?>
                            <span class="help-block"><?php echo $this->errors['email'] ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="form-group <?php echo ($this->errors['category_id']) ? 'has-error' : '' ?> col-md-12 col-md-offset-0">
                        <label for="category_id" class="control-label">Plano</label>
                        <select name="category_id[]" class="form-control control-label">
                            <?php if ($this->auth->admin()) : ?>
                                <option value="0">Selecione uma opção</option>
                            <?php endif; ?>
                            <?php foreach ($this->view->categories as $cat) : ?>
                                <option value="<?php echo $cat->id ?>" <?php foreach ($this->view->user->category as $item) $i = $item->id;
                                                                        if (isset($_POST['cat'])) {
                                                                            $i = $_POST['cat'];
                                                                        }
                                                                        echo ($cat->id == $i) ? 'selected' : ''; ?>>
                                    <?php echo $cat->product ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group <?php echo ($this->errors['cep']) ? 'has-error' : ''; ?> col-md-3 col-md-offset-0">
                        <label for="cep">Cep:</label>
                        <input name="cep" type="text" id="cep" class="form-control" size="10" maxlength="9" onblur="pesquisacep(this.value);" value="<?php echo (isset($this->inputs['cep'])) ? $this->inputs['cep'] : $this->view->user->cep; ?>" />
                        <?php if ($this->errors['cep']) : ?>
                            <span class="help-block"><?php echo $this->errors['cep'] ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="form-group col-md-3 col-md-offset-0">
                        <label for="rua">Rua:</label>
                        <input name="rua" type="text" class="form-control" id="rua" size="60" value="<?php echo (isset($this->inputs['rua'])) ? $this->inputs['rua'] : $this->view->user->rua; ?>" />
                    </div>
                    <div class="form-group col-md-3 col-md-offset-0">
                        <label>Bairro:</label>
                        <input name="bairro" type="text" class="form-control" id="bairro" size="40" value="<?php echo (isset($this->inputs['bairro'])) ? $this->inputs['bairro'] : $this->view->user->bairro; ?>" />
                    </div>
                    <div class="form-group col-md-3 col-md-offset-0">
                        <label for="cidade">Cidade:</label>
                        <input name="cidade" type="text" class="form-control" id="cidade" size="40" value="<?php echo (isset($this->inputs['cidade'])) ? $this->inputs['cidade'] : $this->view->user->cidade; ?>" />
                    </div>
                    <div class="form-group col-md-3 col-md-offset-0">
                        <label for="estado">Estado:</label>
                        <input name="uf" type="text" class="form-control" id="uf" size="2" value="<?php echo (isset($this->inputs['uf'])) ? $this->inputs['uf'] : $this->view->user->uf; ?>" />
                    </div>
                    <div class="form-group col-md-3 col-md-offset-0">
                        <label for="num">Nº:</label>
                        <input name="num" type="text" class="form-control" id="num" value="<?php echo (isset($this->inputs['num'])) ? $this->inputs['num'] : $this->view->user->num; ?>" />
                    </div>
                    <div class="form-group col-md-3 col-md-offset-0">
                        <label for="footer">Tec. responsável: <?php echo $this->view->user->owner->name; ?></label>
                        <input type="hidden" name="owner" class="form-control" value="<?php echo (isset($this->inputs['owner'])) ? $this->inputs['owner'] : $this->view->user->owner->id; ?>" />

                        <ul name="footer" class="actions">
                            <li><a href="/users" class="button special small">Cancelar</a></li>
                            <li><button type="submit" class="button small">Salvar</button></li>
                        </ul>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>