<div class="row">
    <div class="col-xs-12 col-xs-offset-0 col-md-4 col-md-offset-4">
        <div>
            <div class="panel-heading">
                <div><?php $this->renderView('alerts/_errors') ?><?php $this->renderView('alerts/_success'); ?></div>
                <h3 class="panel-title">Para continuar digite o email e senha</h3>
            </div>
            <div class="panel-body">
                <form name="login" action="/login/auth" method="post" accept-charset="utf8">
                    <input type="hidden" name="popup" value="true" />
                    <div class="form-group">
                        <label for="email" class="control-label">Email</label>
                        <input type="text" name="email" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="password" class="control-label">Senha</label>
                        <input type="password" name="password" class="form-control" />
                    </div>
                    <ul class="actions">
                        <li><button type="submit" class="button special">
                                <i class="glyphicon glyphicon-log-in" aria-hidden="true"></i> Entrar
                            </button></li>
                        <li><a href="/user/create">Ainda não é cadastrado?</a></li>
                        <li><a href="/contact">Esqueci minha senha</a></li>
                    </ul>
                </form>
            </div>
        </div>
    </div>
</div>