<?php
header("Access-Control-Allow-Origin: *");
header('Content-Type: application/json');
if ($this->view->check == true) {
    foreach ($this->view->users as $client) {
        if ($client->owner_id == $this->view->auth) {
            foreach ($client->category as $cat) {
                $product = $cat->product;
                $productid = $cat->id;
                $rate = $cat->rate;
            }
            $data = [
                'id' => $client->id,
                'name' => $client->name,
                'email' => $client->email,
                'password' => $client->password,
                'install_password' => $this->view->credential->install_password,
                'owner_id' => $client->owner_id,
                'expires' => $client->expires,
                'category' => $product,
                'category_id' => $productid,
                'rate' => $rate
            ];
            /*foreach($data as $key => $values ){
                echo $values . ',';
            }*/
            $response = json_encode($data);
            echo $response . '|';
        }
    }
} else {
    $data2 = [
        'owner_id' => $this->view->usage->owner_id,
        'month' => $this->view->usage->month,
        'GB_in' => $this->view->usage->GB_in,
        'GB_out' => $this->view->usage->GB_out,
        'date' => $this->view->usage->date
    ];
    $response = json_encode($data2);
    echo $response . '|';
}
